Repository Lightning-AI/litData, pull requests merged in 2025-03, with the labels that each got.

#491 Bump version to 0.2.40
  src/litdata/__about__.py
Labels: bump-version

#499 Update `_get_folder_size`: Reduce Logs noise and switch to `os.scandir`
  src/litdata/streaming/reader.py
  tests/streaming/test_reader.py
Labels: enhancement

#500 Bump: version 0.2.41
  src/litdata/__about__.py
Labels: bump-version

#513 Fix: unsigned s5cmd requests and also add option to disable s5cmd
  README.md
  src/litdata/constants.py
  src/litdata/streaming/downloader.py
  tests/streaming/test_downloader.py
Labels: enhancement, bugfix

#505 Feat: Update indexing of parquet dataset and also add streaming support to huggingface datasets
  src/litdata/constants.py
  src/litdata/processing/readers.py
  src/litdata/streaming/dataset.py
  src/litdata/streaming/downloader.py
  src/litdata/streaming/item_loader.py
  src/litdata/streaming/reader.py
  src/litdata/streaming/writer.py
  src/litdata/utilities/hf_dataset.py
  src/litdata/utilities/parquet.py
  tests/conftest.py
  tests/processing/test_readers.py
  tests/streaming/test_downloader.py
  tests/streaming/test_parquet.py
Labels: enhancement

#523 Update documentation on Streaming Parquet Datasets from Huggingface and other cloud providers
  README.md
  tests/streaming/test_parquet.py
Labels: documentation, enhancement

#525 Bump version to 0.2.43
  src/litdata/__about__.py
Labels: bump-version

#535 Fix: redundant chunk index download request in BinaryReader , when dataset in iter mode
  src/litdata/streaming/reader.py
  tests/streaming/test_dataset.py
Labels: bugfix
