Repository Lightning-AI/litData, pull requests merged in 2025-06, with the labels that each got.

#613 bump version to 0.2.49
  src/litdata/__about__.py
Labels: bump-version

#614 🕒 Add Test Duration Reporting to Pytest in CI
  .github/workflows/ci-testing.yml
Labels: ci / tests

#621 Add Dependabot for Pip & GitHub Actions
  .github/dependabot.yml
Labels: ci / tests

#618 Feat: add transform support for StreamingDataset
  README.md
  src/litdata/streaming/dataset.py
  tests/streaming/test_dataloader.py
  tests/streaming/test_dataset.py
Labels: enhancement

#629 upd: Optimize test (`test_dataset_for_text_tokens_with_large_num_chunks`) to reduce time consumption
  tests/streaming/test_dataset.py
Labels: ci / tests

#628 docs: Update documentation for AWS S3 dataset streaming with `boto3` (including unsigned requests)
  README.md
Labels: documentation

#589 CI: update testing matrix for Python versions (3.12 & 3.13)
  .github/workflows/ci-testing.yml
  requirements/test.txt
  tests/processing/test_functions.py
Labels: ci / tests

#632 Refactor dataset preparation fixture to avoid redundancy and limit test parametrization to reduce time
  tests/conftest.py
  tests/streaming/test_combined.py
Labels: ci / tests
